apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-photo-app-deployment
  labels:
    app: go-photo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-photo-app
  template:
    metadata:
      labels:
        app: go-photo-app
    spec:
      nodeSelector:
        type: backend
      containers:
        - name: go-photo-app
          image: go-photo-app:v-01
          ports:
            - containerPort: 8080